dependencies {
    implementation project(':order-domain')

    implementation 'com.fasterxml.jackson.core:jackson-databind'
    implementation 'org.springframework:spring-context'
    implementation 'org.springframework:spring-tx'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
